### ISSUE TITLE
When a duplicate job is requeued, does it get placed at the back of the queue?

### ISSUE THREAD

**Issue by adambedford** [bartolsthoorn/resque-workers-lock#8]
If so, I could see a situation where job order is not maintained.

**Comment by bartolsthoorn** [comment]
Yes, the original job order is not maintained, but that's just _essential_ to the default purpose of this plugin, i.e. to "continue with _other_ jobs while this type of job is locked". So I am not sure what behaviour you would expect using a workers lock.

**Comment by adambedford** [comment]
Where in the queue would the duplicate job get placed? Would it be at the back of the queue?

**Comment by bartolsthoorn** [comment]
Yes that's correct, and a `Resque::Job::DontPerform` is raised.
This is where that happens: [lock.rb#L55-L57](https://github.com/bartolsthoorn/resque-workers-lock/blob/master/lib/resque/plugins/workers/lock.rb#L55-L57)
